<?php

/**
 * @file
 * Module hooks and alters for the Views Alpha Pagination module.
 */

/**
 * Implements hook_autoload_info().
 */
function alpha_pagination_autoload_info() {
  return array(
    'AlphaPagination' => 'src/AlphaPagination.php',
    'AlphaPaginationCharacter' => 'src/AlphaPaginationCharacter.php',
    'views_handler_area_alpha_pagination' => 'src/views_handler_area_alpha_pagination.inc',
    'views_handler_field_alpha_pagination_group' => 'src/views_handler_field_alpha_pagination_group.inc',
  );
}

/**
 * Implements hook_library_info().
 */
function alpha_pagination_library_info() {
  $libraries['alpha_pagination'] = [
    'title' => 'Views Alpha Pagination',
    'website' => 'https://www.backdropcms.org/project/alpha_pagination',
    'css' => [
      backdrop_get_path('module', 'alpha_pagination') . '/css/alpha_pagination.css' => [],
    ],
  ];
  return $libraries;
}

/**
 * Implements hook_node_presave().
 */
function alpha_pagination_node_presave($entity) {
  cache_clear_all('alpha_pagination:*', 'cache', TRUE);
}

/**
 * Implements hook_token_info().
 *
 * @see \views_handler_area_alpha_pagination::getTokens()
 */
function alpha_pagination_token_info() {
  $info['types']['alpha_pagination'] = [
    'name' => t('Views Alpha Pagination'),
    'description' => t('Tokens related to the current alpha pagination display on the view.'),
    'needs-data' => 'alpha_pagination',
  ];
  $info['tokens']['alpha_pagination']['path'] = [
    'name' => t('Path'),
    'description' => t('The current path of the view (if page display) or current_path().'),
  ];
  $info['tokens']['alpha_pagination']['value'] = [
    'name' => t('Value'),
    'description' => t('The current character value.'),
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 *
 * {@inheritdoc}
 *
 * @see \views_handler_area_alpha_pagination::getTokens()
 */
function alpha_pagination_tokens($type, $tokens, array $data = [], array $options = []) {
  $sanitize = !empty($options['sanitize']);
  $replacements = [];
  if ($type === 'alpha_pagination' && !empty($data['alpha_pagination']) && ($alpha_pagination = $data['alpha_pagination'])) {
    foreach ($tokens as $name => $original) {
      if (isset($alpha_pagination[$name])) {
        $replacements[$original] = $sanitize ? check_plain($alpha_pagination[$name]) : $alpha_pagination[$name];
      }
    }
  }
  return $replacements;
}


/**
 * Implements hook_views_api().
 */
function alpha_pagination_views_api() {
  return [
    'api' => 3,
    'path' => backdrop_get_path('module', 'alpha_pagination') . '/views',
  ];
}

/**
 * Implements hook_views_data().
 */
function alpha_pagination_views_data() {
  $data = [];
  $data['views']['alpha_pagination'] = [
    'title' => t('Alpha Pagination'),
    'group' => 'Global',
    'area' => [
      'help' => t('Adds alphanumeric pagination.'),
      'handler' => 'views_handler_area_alpha_pagination',
    ],
  ];
  $data['views']['alpha_pagination_group'] = [
    'title' => t('Alpha Pagination'),
    'group' => 'Global',
    'field' => [
      'help' => t('Adds an automated field that can be used to group by the alphanumeric pagination prefix.'),
      'handler' => 'views_handler_field_alpha_pagination_group',
    ],
  ];
  return $data;
}
